name = "freerun-builder"
main = "index.js"
compatibility_date = "2026-07-17"

# បន្ថែមផ្នែក [vars] នេះដើម្បីឲ្យ Cloudflare ចងចាំអថេរទាំងនេះជារៀងរហូត
[vars]
GITHUB_OWNER = "FreeRun-Builder"
GITHUB_REPO = "FreeRun-Builder"
